name: 'dbt_olist'
version: '1.0.0'
config-version: 2

profile: 'dbt_olist'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_olist:
    staging:
      +materialized: view
      +schema: olist_silver
    marts:
      +materialized: table
      +schema: olist_gold
