dbt_olist:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID', 'olist-dataops-73908') }}"
      dataset: olist_silver
      threads: 4
      timeout_seconds: 300
      location: us-central1
